CREATE TABLE dados (
    AlunoID int,
    Nome varchar(50),
    Sobrenome varchar(50),
    Endereco varchar(150),
    Cidade varchar(50),
    Host varchar(50)
);
CREATE TABLE CLIENTES (
	ID_CLIENTE INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DATA DA COMPRA DATE NOT NULL,
    LOJA DA COMPRA VARCHAR(50) NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	EMAIL VARCHAR(60),
	TELEFONE VARCHAR(15),
	HOST VARCHAR(50)	
